/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type FeatureHighlight = {
  _type: "featureHighlight";
  title?: string;
  summary?: string;
  status?: "available" | "pilot" | "planned";
};

export type CallToAction = {
  _type: "callToAction";
  label?: string;
  href?: string;
};

export type HelpArticle = {
  _id: string;
  _type: "helpArticle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  audience?: "coach" | "client" | "both";
  category?:
    | "getting-started"
    | "billing"
    | "programmes"
    | "check-ins"
    | "messaging"
    | "privacy-consent";
  summary?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ProductPage = {
  _id: string;
  _type: "productPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  status?: "draft" | "published";
  audience?: "coach" | "client" | "both";
  heroTitle?: string;
  heroText?: string;
  primaryCallToAction?: CallToAction;
  secondaryCallToAction?: CallToAction;
  features?: Array<
    {
      _key: string;
    } & FeatureHighlight
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Seo
  | FaqItem
  | FeatureHighlight
  | CallToAction
  | HelpArticle
  | Slug
  | ProductPage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: PRODUCT_PAGE_QUERY
// Query: *[  _type == "productPage" &&  slug.current == $slug &&  status == "published"][0]{  title,  "slug": slug.current,  heroTitle,  heroText,  primaryCallToAction{    label,    href  },  secondaryCallToAction{    label,    href  },  features[]{    _key,    title,    summary,    status  },  faqs[]{    _key,    question,    answer  },  seo}
export type PRODUCT_PAGE_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  heroTitle: string | null;
  heroText: string | null;
  primaryCallToAction: {
    label: string | null;
    href: string | null;
  } | null;
  secondaryCallToAction: {
    label: string | null;
    href: string | null;
  } | null;
  features: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    status: "available" | "pilot" | "planned" | null;
  }> | null;
  faqs: Array<{
    _key: string;
    question: string | null;
    answer: string | null;
  }> | null;
  seo: Seo | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "productPage" &&\n  slug.current == $slug &&\n  status == "published"\n][0]{\n  title,\n  "slug": slug.current,\n  heroTitle,\n  heroText,\n  primaryCallToAction{\n    label,\n    href\n  },\n  secondaryCallToAction{\n    label,\n    href\n  },\n  features[]{\n    _key,\n    title,\n    summary,\n    status\n  },\n  faqs[]{\n    _key,\n    question,\n    answer\n  },\n  seo\n}': PRODUCT_PAGE_QUERY_RESULT;
  }
}
